kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - yarn install
  - yarn build
  - yarn start
  
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
    repo:
      from_secret: DOCKER_HUB_NAMESPACE/mornin.fm
    registry:
      from_secret: DOCKER_HUB_URL
    auto_tag: true

